/**
 * Google Business Profile reviews for HELICRO (place id ChIJsxZpuLN_0SYRsfUiricvL0Y).
 * Every review is 5 stars. `text` is omitted for rating-only reviews.
 */
export interface GoogleReview {
  name: string;
  stars: 1 | 2 | 3 | 4 | 5;
  text?: string;
  reviewUrl: string;
  /** Language of the review text (BCP 47). */
  lang: 'en' | 'fr' | 'nl' | 'el' | 'hr' | 'it';
}

export const GOOGLE_PLACE_ID = 'ChIJsxZpuLN_0SYRsfUiricvL0Y';
export const GOOGLE_MAPS_URL = `https://www.google.com/maps/search/?api=1&query=HELICRO&query_place_id=${GOOGLE_PLACE_ID}`;
export const GOOGLE_WRITE_REVIEW_URL = `https://search.google.com/local/writereview?placeid=${GOOGLE_PLACE_ID}`;

const R = 'https://www.google.com/maps/reviews/data=!4m8!14m7!1m6!2m5!1s';
const S = '!2m1!1s0x0:0x462f2f27ae22f5b1!3m1!1s2@1:';

export const googleReviews: GoogleReview[] = [
  { name: 'George K', stars: 5, lang: 'en', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT2pkbFFsRnNSREE1VjE5d09IVnhZVzl5TlZWSmNGRRAB${S}CAIQACodChtycF9oOjdlQlFsRDA5V19wOHVxYW9yNVVJcFE%7C%7C?hl=en` },
  { name: 'Fabio Bortolussi', stars: 5, lang: 'en', text: 'We were extremely happy with the service! Gerasimos was professional, reliable and punctual, and went out of his way to make sure everything went smoothly for our family. We really appreciated his care and dedication to providing the best possible service. We highly recommend him to anyone looking for a reliable transfer in Brussels. Thank you, Gerasimos!', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT2psRU4xZDZORU5VZW1KaFZYVnJRM2RCWkUwemMxRRAB${S}CAIQACodChtycF9oOjlEN1d6NENUemJhVXVrQ3dBZE0zc1E%7C%7C?hl=en` },
  { name: 'Γεράσιμος Λύτρας', stars: 5, lang: 'el', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT25KalZXNVZTelJJU25sVmFYTmZWM1E0ZWkwM2IxRRAB${S}CAIQACodChtycF9oOnJjVW5VSzRISnlVaXNfV3Q4ei03b1E%7C%7C?hl=en` },
  { name: 'Andrea Guerri', stars: 5, lang: 'en', text: 'Great experience. Gerasimos was an excellent driver and a very kind person', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT21weGJ6TTJXRU0xVlhaMk1UWlpTSE5HZWpKWFRtYxAB${S}CAIQACodChtycF9oOmpxbzM2WEM1VXZ2MTZZSHNGejJXTmc%7C%7C?hl=en` },
  { name: 'Christelle Zentar', stars: 5, lang: 'fr', text: 'Chauffeur ponctuel, agréable et très respectueux même à 4h du matin. Merci beaucoup!! Je recommande.', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT25JMlNVYzJXRU16YmxNM1FXeFJiRlEwYjJsamRsRRAB${S}CAIQACodChtycF9oOnI2SUc2WEMzblM3QWxRbFQ0b2ljdlE%7C%7C?hl=en` },
  { name: 'Sara Corvelyn', stars: 5, lang: 'nl', text: 'We waren nogal last-minute met het regelen van vervoer van luchthaven Charleroi naar Brussel-Zuid, maar dat bleek totaal geen probleem. Vanaf het eerste contact verliep alles echt perfect: duidelijke en directe communicatie, zonder ingewikkeld platform of gedoe. De chauffeur stond super stipt klaar, was heel vriendelijk en bood ons zelfs water aan. Omdat alles zo vlot verliep, hebben we uiteindelijk beslist om ons meteen helemaal tot thuis in Beernem te laten brengen, en daar hebben we geen seconde spijt van gehad. De taxi was heel ruim voor ons vijven, kraaknet en comfortabel. Onze chauffeur reed vlot en veilig en was bovendien heel aangenaam om onderweg een babbeltje mee te slaan. Wij kunnen dit taxibedrijf alleen maar van harte aanbevelen. Als we in de toekomst opnieuw luchthavenvervoer nodig hebben, weten we alvast wie we bellen!', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT20xVFpIcHFRVmx4UWt0MFNGVnZjRXhVVFd4TVUyYxAB${S}CAIQACodChtycF9oOm1TZHpqQVlxQkt0SFVvcExUTWxMU2c%7C%7C?hl=en` },
  { name: 'Sarith Phon', stars: 5, lang: 'it', text: 'Ottimo servizio e autista molto gentile che ci ha dato molti consigli. Prezzo giusto per un servizio super.', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT2tOclJWWnpaWEpUVkhkVFMwdDNPV2xVU2s1WU5uYxAB${S}CAIQACodChtycF9oOkNrRVZzZXJTVHdTS0t3OWlUSk5YNnc%7C%7C?hl=en` },
  { name: 'Ivona Malbasic', stars: 5, lang: 'en', text: 'Always very friendly and professional service. My first choice for airport transfers in Brussels', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT2xwMmQzSnlURGxVV0VwbWQyWmtYMm8xTkRsUmNVRRAB${S}CAIQACodChtycF9oOlp2d3JyTDlUWEpmd2ZkX2o1NDlRcUE%7C%7C?hl=en` },
  { name: 'Nour Sobh', stars: 5, lang: 'en', text: 'Amazing service, super friendly, great spacious cars, super patient with multiple drop-offs, child seat available of different sizes, fast response, amazing value for money.', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT25FNU1XVkVjRWxrZURaV1JqRndhbVZTU0VORGVFRRAB${S}CAIQACodChtycF9oOnE5MWVEcElkeDZWRjFwamVSSENDeEE%7C%7C?hl=en` },
  { name: 'Lorena Bestulić', stars: 5, lang: 'hr', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT2prd1lXMVBjMVpYV0VSaE1qWkRUREpLTmpkYVlsRRAB${S}CAIQACodChtycF9oOjkwYW1Pc1ZXWERhMjZDTDJKNjdaYlE%7C%7C?hl=en` },
  { name: 'Ivana Ruzic', stars: 5, lang: 'en', text: 'Great service: reliable and safe driver with a high quality vehicle!', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT2xneE4zRk1TVlpJYmtaUmFFTm1aMjl0TFdzd1ZXYxAB${S}CAIQACodChtycF9oOlgxN3FMSVZIbkZRaENmZ29tLWswVWc%7C%7C?hl=en` },
  { name: 'Matej Kovačević', stars: 5, lang: 'en', text: 'Perfect experience on several occasions, highly recommended!', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT25obVJHMXdlVGREVEZBMWFsQnFhamg2UjJSVk4yYxAB${S}CAIQACodChtycF9oOnhmRG1weTdDTFA1alBqajh6R2RVN2c%7C%7C?hl=en` },
  { name: 'Martina Lozo', stars: 5, lang: 'hr', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT2tsU1kxSm5iR1J1ZWxWdkxVOHRNblZTUldWTFRHYxAB${S}CAIQACodChtycF9oOklSY1JnbGRuelVvLU8tMnVSRWVLTGc%7C%7C?hl=en` },
  { name: 'A Mažuranić', stars: 5, lang: 'en', text: 'Very professional and nice service. I always choose Helicro.', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT20xdlZtcFNVbmRPVm5adllsa3lUVll5ZERsYVRtYxAB${S}CAIQACodChtycF9oOm1vVmpSUndOVnZvYlkyTVYydDlaTmc%7C%7C?hl=en` },
  { name: 'Vladimir', stars: 5, lang: 'en', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT2tGTGEyeEdkRkp5UkZZNU5sTmhRa1I1ZVVFNVYyYxAB${S}CAIQACodChtycF9oOkFLa2xGdFJyRFY5NlNhQkR5eUE5V2c%7C%7C?hl=en` },
  { name: 'Anamaria Bolf', stars: 5, lang: 'hr', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT201VGMweGZlazE1Ym1WM1dqRlNjamg2WVVjek5sRRAB${S}CAIQACodChtycF9oOm5Tc0xfek15bmV3WjFScjh6YUczNlE%7C%7C?hl=en` },
  { name: 'Sandra Rencelj', stars: 5, lang: 'en', text: 'Great experiance. On time, safe driver and very comfortable car. Absolutely can recommend.', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT25CNlNrdG5jak0wT1hoamFTMTBSM0JxWTFkR00zYxAB${S}CAIQACodChtycF9oOnB6SktncjM0OXhjaS10R3BqY1dGM3c%7C%7C?hl=en` },
  { name: 'Igor Šlosar', stars: 5, lang: 'en', text: 'Fantastic service. Punctual, fast, clean, and on-time. Preferred choice of transfer when in Bruxelles.', reviewUrl: `${R}Ci9DQUlRQUNvZENodHljRjlvT25KNU9WWkJRbEZKVlhodGJHNVlSMjUzZEMxMlpuYxAB${S}CAIQACodChtycF9oOnJ5OVZBQlFJVXhtbG5YR253dC12Znc%7C%7C?hl=en` },
  { name: 'Josipa Špoljarić', stars: 5, lang: 'en', text: 'I’ve had a great experience with Mr. Gerasimos and Helicro Services. He is incredibly friendly, reliable, and always puts the customer first. Every time I’ve booked a ride, he confirmed my request very quickly and was always accommodating, even when I needed to adjust my pickup time on short notice due to delays at the airport. The website is easy to use, making booking fast and convenient. I’ve also arranged rides for my family and friends, and all of them had a smooth experience and found it easy to meet up with Mr. Gerasimos. I highly recommend Helicro Services to anyone looking for reliable and professional airport transfers.', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnTUNZa0xmVFVBEAE${S}CIHM0ogKEICAgMCYkLfTUA%7C%7C?hl=en` },
  { name: 'Tenia Pappa', stars: 5, lang: 'en', text: 'I have used a lot of transport services in Belgium but Gerasimos was the best. The car was very clean and Gerasimos was very friendly and polite.', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnTUNnbjRMMXpRRRAB${S}CIHM0ogKEICAgMCgn4L1zQE%7C%7C?hl=en` },
  { name: 'Spyros Mazarakis', stars: 5, lang: 'en', text: 'Gerasimos is always providing me outstanding services. He is my only choice whenever I visit Belgium, either for airport transfers or any of my movements around. Always punctual, pleasant and kind, he drives extremely carefully, making the journey so smooth and enjoyable an experience. Always acting and behaving proactively, professionally and to the point yet a pleasant and enjoyable personality. He is always delivering the most comfortable, not driving but, experience.', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnTUNna191UVd3EAE${S}CIHM0ogKEICAgMCgk_uQWw%7C%7C?hl=en` },
  { name: 'Γεώργιος Νάστας', stars: 5, lang: 'el', text: 'Πολύ εξυπηρετικό προσωπικό. Με βοήθησαν σε ότι χρειάστηκα στο Βέλγιο.', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnTUNndGF6cWRBEAE${S}CIHM0ogKEICAgMCgtazqdA%7C%7C?hl=en` },
  { name: 'Yannis Lytras', stars: 5, lang: 'en', text: 'Great ride! Clean car and Gerasimos is very polite!', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnTUNnaWJfcnBnRRAB${S}CIHM0ogKEICAgMCgib_rpgE%7C%7C?hl=en` },
  { name: 'Ivana Marasovic', stars: 5, lang: 'hr', text: 'Nova i čista vozila. Osoblje profesionalno, usluga za preporučiti. Vidimo se opet!', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnTUNnOGJhZklnEAE${S}CIHM0ogKEICAgMCg8bafIg%7C%7C?hl=en` },
  { name: 'Mi smo', stars: 5, lang: 'en', text: 'One grandmother delivered to our kids quickly, safely and happily! Gerasimos made sure all the angles were covered; meet and greet, comfort, speed, language barriers... nothing was a problem. He even took care of the luggage and umbrella detail during the rain. Helicro team exceeded our expectations and will definitely be our port of call in the future!', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnTURBZ19IRE5BEAE${S}CIHM0ogKEICAgMDAg_HDNA%7C%7C?hl=en` },
  { name: 'Maro Dodig', stars: 5, lang: 'en', text: 'Riding with Gerasimos was the best. He is very punctual, very safe and very reliable. His discipline seems like he is in the army. He picked us all up on time, planned the best route, knew when and where the traffic jams are, made sure we are comfortable and are not thirsty during our trip. Can’t get any better. Keep it up!!!', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnTURBLVk3aGd3RRAB${S}CIHM0ogKEICAgMDA-Y7hgwE%7C%7C?hl=en` },
  { name: 'Jelena Despot', stars: 5, lang: 'en', text: 'Outstanding service, very comfortable rides, always on time!! Highly recomended!!', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnTURBdk56ci13RRAB${S}CIHM0ogKEICAgMDAvNzr-wE%7C%7C?hl=en` },
  { name: 'Ioannis Kleisiaris', stars: 5, lang: 'el', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUNuOHJpOHpnRRAB${S}CIHM0ogKEICAgICn8ri8zgE%7C%7C?hl=en` },
  { name: 'Ingrid Bozin', stars: 5, lang: 'en', text: 'HELICRO transport is the best door-to-door transport service I ever used. The owner is extremly professional and responsive, yet very human and attentive to particular needs. The cars/vans are of high standard and the communication is flawless. I can certainly recommend it to anyone.', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnSUNuMHJqNmNnEAE${S}CIHM0ogKEICAgICn0rj6cg%7C%7C?hl=en` },
  { name: 'Anna Georgiou', stars: 5, lang: 'en', text: 'Very helpful and friendly approach. Easy booking procedure and reasonable prices. Highly recommended!', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUNuNkxILWhBRRAB${S}CIHM0ogKEICAgICn6LH-hAE%7C%7C?hl=en` },
  { name: 'Irene Arto Escuredo', stars: 5, lang: 'en', text: 'Gerasimos provided an outstanding service. Always punctual, pleasant and kind, he drives with great care, making the journey smooth and enjoyable. What truly sets him apart is his willingness to help and to find solutions to any issue that might arise. He consistently goes the extra mile for his clients, ensuring a stress-free experience. He also gave me some great tips for exploring Brussels, which was much appreciated! Gerasimos is not only reliable but also engaging, with a friendly conversation that adds to the overall comfort of the trip. I can’t recommend his services enough!', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnSURIM1A3R2NREAE${S}CIHM0ogKEICAgIDH3P7GcQ%7C%7C?hl=en` },
  { name: 'Ivana Rudić Burčul', stars: 5, lang: 'en', text: 'Very kind and professional. They provided a solution for a transfer from CRL airport to Brussels even the flight was delayed for few hours.', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUNId2FTMGx3RRAB${S}CIHM0ogKEICAgICHwaS0lwE%7C%7C?hl=en` },
  { name: 'Vaia Vaena', stars: 5, lang: 'en', text: 'Great service and communication.', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUNMeDkzZ3JRRRAB${S}CIHM0ogKEICAgICLx93grQE%7C%7C?hl=en` },
  { name: 'Paja Stojkovic', stars: 5, lang: 'en', text: 'Excellent driver, very professional', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUNMMGN2TzdRRRAB${S}CIHM0ogKEICAgICL0cvO7QE%7C%7C?hl=en` },
  { name: 'Elisa Aonzo', stars: 5, lang: 'en', text: 'I use Helicro to get to and from Charleroi Airport. Gerasimos is the most professional driver in Brussels. Always on time and with good quality vehicles.', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUR6MWVXV3ZnRRAB${S}CIHM0ogKEICAgIDz1eWWvgE%7C%7C?hl=en` },
  { name: 'Tania Dimou', stars: 5, lang: 'en', text: 'Extremely professional transport services from/to airports but also within Brussels (I also used the service to move within Brussels). Gerasimos is an absolutely reliable, kind and professional person. You are going to receive timely and to the point information about the pick-up time and the other information related with the transport. On the date of the transport, he is perfectly on time. You are going to enjoy a comfortable ride in the new van. Gerasimos drives very carefully and smoothly. It is highly recommended.', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnSUR6eHZ6RkZnEAE${S}CIHM0ogKEICAgIDzxvzFFg%7C%7C?hl=en` },
  { name: 'Aliki Psaila', stars: 5, lang: 'fr', text: 'Voyage très agréable avec Gerasimos. Très prudent à la conduite, très ponctuel et gentil avec les clients. Je recommande fortement. Merci et à très bientôt!', reviewUrl: `${R}ChZDSUhNMG9nS0VJQ0FnSUR6aHFURU9REAE${S}CIHM0ogKEICAgIDzhqTEOQ%7C%7C?hl=en` },
  { name: 'Tfarrah Hanafi Erguibi', stars: 5, lang: 'en', text: 'I traveled with Gerasimos and it has been a very pleasant experience. He is careful driving, so that is a plus, but on top of that, he is an interesting person and his music is excellent. He made my trip very enjoyable, without a doubt, I recommend it, and I’ll call him for my next trips :). He also acted as a guide for me, explaining interesting things about the country.', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUR6dXR1WTVnRRAB${S}CIHM0ogKEICAgIDzutuY5gE%7C%7C?hl=en` },
  { name: 'Georgios Konstantinou', stars: 5, lang: 'el', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUR6d3NXczRRRRAB${S}CIHM0ogKEICAgIDzwsWs4QE%7C%7C?hl=en` },
  { name: 'Massimiliano Luca Dragoni', stars: 5, lang: 'en', text: 'Excellent service, always punctual and very polite. The company goes an extra mile to meet the needs of customers to their satisfaction. I strongly suggest them for service to Charleroi.', reviewUrl: `${R}ChdDSUhNMG9nS0VJQ0FnSUR6Z3R6TjdBRRAB${S}CIHM0ogKEICAgIDzgtzN7AE%7C%7C?hl=en` },
];

export const REVIEW_COUNT = googleReviews.length;
export const AVERAGE_RATING = Number((googleReviews.reduce((s, r) => s + r.stars, 0) / REVIEW_COUNT).toFixed(1));

/** Reviews that carry text, longest first is not wanted; keep Google order but text-only. */
export const reviewsWithText = googleReviews.filter((r): r is GoogleReview & { text: string } => Boolean(r.text));
