// Programmatic registry for the routes with a published fixed price (Helicro price list, September 2026).
// One entry per route and language; content is generated by src/lib/seoContent/pricedRoute.ts.
import { DESTINATIONS, PRICED_ROUTES, SHARED_SHUTTLE, type PricedRoute } from './seoFacts';
import type { SEOPage } from './seoPages';

export type PricedLang = 'en' | 'nl' | 'fr';

/** URL per language for every priced route that gets its own page. Lille EN uses the existing airport hub. */
export const PRICED_ROUTE_URLS: Record<string, Partial<Record<PricedLang, string>>> = {
  'crl-antwerp': { en: '/en/route/charleroi-airport-antwerp', nl: '/nl/route/charleroi-airport-antwerpen', fr: '/fr/navette/charleroi-aeroport-anvers' },
  'crl-ghent': { en: '/en/route/charleroi-airport-ghent', nl: '/nl/route/charleroi-airport-gent', fr: '/fr/navette/charleroi-aeroport-gand' },
  'crl-bruges': { en: '/en/route/charleroi-airport-bruges', nl: '/nl/route/charleroi-airport-brugge', fr: '/fr/navette/charleroi-aeroport-bruges' },
  'brussels-lille-airport': { en: '/en/airport-transfer/lille', nl: '/nl/route/brussel-rijsel-luchthaven', fr: '/fr/navette/bruxelles-lille-aeroport' },
  'brussels-paris-cdg': { en: '/en/route/brussels-paris-cdg', nl: '/nl/route/brussel-parijs-cdg', fr: '/fr/navette/bruxelles-paris-cdg' },
  'brussels-paris-orly': { en: '/en/route/brussels-paris-orly', nl: '/nl/route/brussel-parijs-orly', fr: '/fr/navette/bruxelles-paris-orly' },
  'brussels-eindhoven': { en: '/en/route/brussels-eindhoven', nl: '/nl/route/brussel-eindhoven', fr: '/fr/navette/bruxelles-eindhoven' },
  'brussels-amsterdam': { en: '/en/route/brussels-amsterdam', nl: '/nl/route/brussel-amsterdam', fr: '/fr/navette/bruxelles-amsterdam' },
  'brussels-maastricht': { en: '/en/route/brussels-maastricht', nl: '/nl/route/brussel-maastricht', fr: '/fr/navette/bruxelles-maastricht' },
  'brussels-dusseldorf': { en: '/en/route/brussels-dusseldorf', nl: '/nl/route/brussel-dusseldorf', fr: '/fr/navette/bruxelles-dusseldorf' },
  'brussels-cologne': { en: '/en/route/brussels-cologne', nl: '/nl/route/brussel-keulen', fr: '/fr/navette/bruxelles-cologne' },
  'brussels-frankfurt': { en: '/en/route/brussels-frankfurt', nl: '/nl/route/brussel-frankfurt', fr: '/fr/navette/bruxelles-francfort' },
  'brussels-luxembourg': { en: '/en/route/brussels-luxembourg', nl: '/nl/route/brussel-luxemburg', fr: '/fr/navette/bruxelles-luxembourg' },
};

/** Routes whose EN page is built elsewhere (airport hub); the generator skips them for that language. */
const EXTERNAL_PAGES = new Set(['/en/airport-transfer/lille']);

export const SHARED_SHUTTLE_URLS: Record<PricedLang, string> = {
  en: '/en/route/brussels-charleroi-shared-shuttle',
  nl: '/nl/route/brussel-charleroi-gedeelde-shuttle',
  fr: '/fr/navette/bruxelles-charleroi-navette-partagee',
};

export const PRICE_LIST_URLS: Record<PricedLang, string> = {
  en: '/price-list',
  nl: '/nl/prijslijst',
  fr: '/fr/tarifs',
};

const FROM: Record<PricedLang, Record<'brussels' | 'crl', string>> = {
  en: { brussels: 'Brussels', crl: 'Charleroi Airport' },
  nl: { brussels: 'Brussel', crl: 'Charleroi Airport' },
  fr: { brussels: 'Bruxelles', crl: 'Aéroport de Charleroi' },
};

function short(name: string): string {
  // "Paris Charles de Gaulle Airport" -> keep; used in titles as-is but trimmed of "(...)".
  return name.replace(/\s*\(.*\)$/, '');
}

function buildPage(route: PricedRoute, lang: PricedLang, url: string): SEOPage {
  const d = DESTINATIONS[route.to];
  const from = FROM[lang][route.from];
  const to = short(d.name[lang]);
  const [t1, t2] = route.tiers;
  const leg = route.from === 'crl' ? d.fromCRL! : d.fromBrussels;
  const isCrl = route.from === 'crl';
  if (lang === 'en') {
    return {
      type: isCrl ? 'Priced route (CRL)' : 'Priced route',
      url,
      h1: `${from} to ${to} private transfer at a fixed price`,
      keyword: `${from.toLowerCase()} to ${to.toLowerCase()} transfer`,
      title: `${from} to ${to} Transfer | Fixed Price From ${t1.price}€ per Minivan | Helicro`,
      description: `Private minivan from ${isCrl ? 'Charleroi Airport' : 'Brussels or Brussels Airport'} to ${d.scope.en}: ${t1.price}€ for 1–3 passengers, ${t2.price}€ for 4–8, per vehicle, door to door. About ${leg.km} km, ${leg.minMin}–${leg.maxMin} min. Book 24/7.`,
      priority: isCrl ? 'HIGH' : 'MEDIUM',
    };
  }
  if (lang === 'nl') {
    return {
      type: isCrl ? 'Priced route (CRL)' : 'Priced route',
      url,
      h1: `Privévervoer ${from} – ${to} met vaste prijs`,
      keyword: `taxi ${from.toLowerCase()} ${to.toLowerCase()}`,
      title: `Taxi ${from} – ${to} | Vaste prijs vanaf ${t1.price}€ per minivan | Helicro`,
      description: `Privé minivan van ${isCrl ? 'Charleroi Airport' : 'Brussel of Brussels Airport'} naar ${d.scope.nl}: ${t1.price}€ voor 1–3 passagiers, ${t2.price}€ voor 4–8, per voertuig, van deur tot deur. Ongeveer ${leg.km} km, ${leg.minMin}–${leg.maxMin} min. Boek 24/7.`,
      priority: isCrl ? 'HIGH' : 'MEDIUM',
    };
  }
  return {
    type: isCrl ? 'Priced route (CRL)' : 'Priced route',
    url,
    h1: `Navette privée ${from} – ${to} à prix fixe`,
    keyword: `navette ${from.toLowerCase()} ${to.toLowerCase()}`,
    title: `Navette ${from} – ${to} | Prix fixe dès ${t1.price}€ par minivan | Helicro`,
    description: `Minivan privé depuis ${isCrl ? 'l’aéroport de Charleroi' : 'Bruxelles ou Brussels Airport'} vers ${d.scope.fr} : ${t1.price}€ pour 1–3 passagers, ${t2.price}€ pour 4–8, par véhicule, porte à porte. Environ ${leg.km} km, ${leg.minMin}–${leg.maxMin} min. Réservation 24/7.`,
    priority: isCrl ? 'HIGH' : 'MEDIUM',
  };
}

const SHARED_PAGES: Record<PricedLang, SEOPage> = {
  en: {
    type: 'Shared shuttle',
    url: SHARED_SHUTTLE_URLS.en,
    h1: `Shared shuttle Brussels to Charleroi Airport from ${SHARED_SHUTTLE.perPassengerDay}€ per person`,
    keyword: 'shared shuttle brussels charleroi airport',
    title: `Shared Shuttle Brussels – Charleroi Airport | ${SHARED_SHUTTLE.perPassengerDay}€ per Person, Door to Door | Helicro`,
    description: `Seat-in-van shuttle between any Brussels address and Charleroi Airport: ${SHARED_SHUTTLE.perPassengerDay}€ per person by day, ${SHARED_SHUTTLE.perPassengerNight}€ at night, pickup at your door, flight tracked, luggage included. Cheaper than a private taxi, easier than the Flibco bus.`,
    priority: 'HIGH',
  },
  nl: {
    type: 'Shared shuttle',
    url: SHARED_SHUTTLE_URLS.nl,
    h1: `Gedeelde shuttle Brussel – Charleroi Airport vanaf ${SHARED_SHUTTLE.perPassengerDay}€ per persoon`,
    keyword: 'gedeelde shuttle brussel charleroi',
    title: `Gedeelde shuttle Brussel – Charleroi Airport | ${SHARED_SHUTTLE.perPassengerDay}€ per persoon, deur tot deur | Helicro`,
    description: `Shuttle met gedeelde minivan tussen elk Brussels adres en Charleroi Airport: ${SHARED_SHUTTLE.perPassengerDay}€ per persoon overdag, ${SHARED_SHUTTLE.perPassengerNight}€ ’s nachts, ophaling aan huis, vluchtopvolging, bagage inbegrepen. Goedkoper dan een privétaxi, makkelijker dan de Flibco-bus.`,
    priority: 'HIGH',
  },
  fr: {
    type: 'Shared shuttle',
    url: SHARED_SHUTTLE_URLS.fr,
    h1: `Navette partagée Bruxelles – aéroport de Charleroi dès ${SHARED_SHUTTLE.perPassengerDay}€ par personne`,
    keyword: 'navette partagée bruxelles charleroi',
    title: `Navette partagée Bruxelles – Aéroport de Charleroi | ${SHARED_SHUTTLE.perPassengerDay}€ par personne, porte à porte | Helicro`,
    description: `Navette en minivan partagé entre toute adresse bruxelloise et l’aéroport de Charleroi : ${SHARED_SHUTTLE.perPassengerDay}€ par personne le jour, ${SHARED_SHUTTLE.perPassengerNight}€ la nuit, prise en charge à domicile, suivi de vol, bagages inclus. Moins cher qu’un taxi privé, plus simple que le bus Flibco.`,
    priority: 'HIGH',
  },
};

/** All generated SEOPage entries (routes with a fixed price plus the shared shuttle), all languages. */
export const pricedRoutePages: SEOPage[] = [
  ...PRICED_ROUTES.flatMap((route) => {
    const urls = PRICED_ROUTE_URLS[route.key];
    if (!urls) return [];
    return (Object.keys(urls) as PricedLang[])
      .filter((lang) => !EXTERNAL_PAGES.has(urls[lang]!))
      .map((lang) => buildPage(route, lang, urls[lang]!));
  }),
  SHARED_PAGES.en,
  SHARED_PAGES.nl,
  SHARED_PAGES.fr,
];

/** Resolve a URL to the priced route it represents. */
export function pricedRouteFor(url: string): { route: PricedRoute; lang: PricedLang } | null {
  for (const route of PRICED_ROUTES) {
    const urls = PRICED_ROUTE_URLS[route.key];
    if (!urls) continue;
    for (const lang of Object.keys(urls) as PricedLang[]) {
      if (urls[lang] === url && !EXTERNAL_PAGES.has(url)) return { route, lang };
    }
  }
  return null;
}

export function sharedShuttleLangFor(url: string): PricedLang | null {
  const hit = (Object.keys(SHARED_SHUTTLE_URLS) as PricedLang[]).find((l) => SHARED_SHUTTLE_URLS[l] === url);
  return hit ?? null;
}
